//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:2.0.50727.3082
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("BabBot")]
[assembly: AssemblyDescription("BabBot your servant")]
[assembly: AssemblyCompany("https://sourceforge.net/projects/babbot/")]
[assembly: AssemblyProduct("BabBot")]
[assembly: AssemblyCopyright("Copyright (C) BabBot Team 2009")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(true)]
[assembly: Guid("d038566a-1937-478a-b5c5-b79c4afb253d")]
[assembly: AssemblyVersion("1.0.0.178")]
[assembly: AssemblyFileVersion("1.0.0.178")]


